# Generated by Django 5.1.3 on 2024-11-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='photo1/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photo2/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photo3/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('payment_mode', models.CharField(choices=[('cod', 'Cash on Delivery'), ('upi', 'UPI')], default='cod', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explore.product')),
            ],
        ),
    ]
